services:
    
    # custom fosuser registration form handler
    pugx_user.form.handler.registration:
        class: PUGX\MultiUserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator.default", "@pugx_user.manager.user_discriminator"]
        scope: request
        public: false
    
    # custom fosuser profile form handler
    pugx_user.form.handler.profile:
        class: PUGX\MultiUserBundle\Form\Handler\ProfileFormHandler
        arguments: ["@fos_user.profile.form", "@request", "@fos_user.user_manager", "@pugx_user.manager.user_discriminator"]
        scope: request
        public: false
    
    # class to discriminate users types
    pugx_user.manager.user_discriminator:
        class:     PUGX\MultiUserBundle\Manager\UserDiscriminator
        arguments: ["@service_container", %pugx_user_discriminator_parameters%]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: security.manual_login }
            
    pugx_multi_user.orm.validator.unique:
        class: PUGX\MultiUserBundle\Validator\Constraints\UniqueEntityValidator
        tags:
            - { name: validator.constraint_validator, alias: pugx.orm.validator.unique }
        arguments: [ "@doctrine" ]
                
    # alias
    pugx_user_registration_form_handler:
        alias: pugx_user.form.handler.registration
    pugx_user_profile_form_handler:
        alias: pugx_user.form.handler.profile
    pugx_user_discriminator:
        alias: pugx_user.manager.user_discriminator
    
    