language: php

php:
  - 5.3
  - 5.4
  
sudo: false  
  
before_install:
  - curl -sS https://getcomposer.org/installer | php

install: 
  - php composer.phar update --verbose
    
script:
  - phpunit

notifications:
  email:
    - leonardo.proietti@gmail.com

